CREATE DATABASE task3;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(30) NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT current_timestamp() ON UPDATE CURRENT_TIMESTAMP(),
    comment TEXT NOT NULL,
    PRIMARY KEY (id)
)
ENGINE = InnoDB;